In [1]:
import numpy as np

In [2]:
np_height = np.array([1.73, 1.68, 1.71, 1.89, 1.79])

np_weight = np.array([65.4 , 59.2, 63.6, 88.4, 68.7])

bmi = np_weight / np_height ** 2

bmi

array([21.85171573, 20.97505669, 21.75028214, 24.7473475 , 21.44127836])

In [3]:
bmi >23

array([False, False, False,  True, False])

In [6]:
np.round(bmi[bmi>23],2)

array([24.75])

In [12]:
2!=3

True

In [19]:
z= 4
if z%2 == 0:
    print("z is even")


z is even


In [27]:
z= 5
if z%2 == 0:
    print("checking " + str(z))
    print("z is even")
else :
    print("z is odd")



z is odd


In [32]:
age = 4
if age >4 :
    print("you can enter class")
elif age == 4 :
    print("you can enter pre-school")
else :
    print("you cannot enter class")


you can enter pre-school


In [33]:
z = 3
if z%2 ==0 :
    print("z us divisible by 2")
elif z%3==0 : 
    print("z is divisible by 3")
else:
    print("z is not divisible")

z is divisible by 3


In [34]:
#Logic, Control Flow and Filtering

#Equality
# Comparison of booleans
print(True == False)

False


In [35]:
-5 *15 != 75 # Comparison of integers

True

In [38]:
print("pyscript" == "Pyscript") # Comparison of strings

False


In [39]:
print (True ==1) # Compare a boolean with a numeric

True


In [40]:
# Comparison of integers
x = -3*6
print(x >= -10)

False


In [41]:
y = "test"

print ("test" <= y)

True


In [42]:
print(True > False)

True


In [44]:
my_home = np.array([18.0, 20.0, 10.75, 9.50])
your_home = np.array([14.0, 24.0, 14.25, 9.0])
print(my_home >=18)

[ True  True False False]


In [50]:
my_home[my_home >=18]

array([18., 20.])

In [51]:
print(my_home > your_home)

[ True False False  True]


In [52]:
# and, or, not (1)
# Define variables
my_kitchen = 18.0
your_kitchen = 14.0

# my_kitchen bigger than 10 and smaller than 18?

print(my_kitchen > 10 and my_kitchen <18)

False


In [54]:
# my_kitchen smaller than 14 or bigger than 17?

print(my_kitchen < 14 or my_kitchen >17)


True


In [55]:
# Double my_kitchen smaller than triple your_kitchen?

print( 2* my_kitchen < 3* your_kitchen)

True


In [59]:
#Boolean operators with Numpy
# Create arrays
# my_house greater than 18.5 or smaller than 10

print(np.logical_or(my_home> 18.5, my_home<10))

[False  True False  True]


In [62]:
print(my_home> 18.5 or my_home<10) #normal or not working so need to use np.logical_or

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [64]:
# Both my_house and your_house smaller than 11

print(np.logical_and(my_home<11,your_home<11))

[False False False  True]


In [66]:
room = "kit"
area = 14.0

if room == "kit":
    print("looking around in the kitchen.")
else:
    print("looking around elsewhere.")

looking around in the kitchen.


In [67]:
# if statement for area
if area > 15:
    print("big place!")
else:
    print("pretty small.")

pretty small.


In [69]:
room = "bed"
area = 14
if room =="kit":
    print("looking around in the kitchen.")
elif room == "beda
    print("looking around in the bedroom.")
else:
    print("looking around elsewhere")


looking around in the bedroom.


In [71]:
room = "bed"
area = 14
if room =="kit":
    if area > 15:
        print("big kitchen")
    else:
        print("small kitchen")
elif room == "bed":
    if area < 15:
        print("small bedroom")
    else:
        print("big bedroom")
else:
    print("looking around elsewhere")


small bedroom


In [84]:
import pandas as pd
cars1 = pd.read_csv("https://raw.githubusercontent.com/akjadon/HH/master/Python/DS_tutorial_trn/2.Intermediate%20Python%20for%20Data%20Science/Datasets/cars.csv",sep=',', index_col = [0])

#cars1.set_index(cars1.columns[0],inplace = True)

In [80]:
cars1.head()

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False
IN             18          India         False
RU            200         Russia          True

In [81]:
#Extract drives_right column as Series: dr

dr = cars1["drives_right"]
dr

US      True
AUS    False
JAP    False
IN     False
RU      True
MOR     True
EG      True
Name: drives_right, dtype: bool

In [82]:
# Use dr to subset cars: sel
sel = cars1[dr]
sel

cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [87]:
sel = cars1[cars1['drives_right']]
sel

cars_per_cap        country  drives_right
US            809  United States          True
RU            200         Russia          True
MOR            70        Morocco          True
EG             45          Egypt          True

In [91]:
#Create car_maniac: observations that have a cars_per_cap over 500
car_maniac = cars1[cars1.cars_per_cap>500]
car_maniac

cars_per_cap        country  drives_right
US            809  United States          True
AUS           731      Australia         False
JAP           588          Japan         False

In [93]:
#Create medium: observations with cars_per_cap between 100 and 500
medium = cars1[(cars1.cars_per_cap<500) & (cars1.cars_per_cap>100)]
medium

cars_per_cap country  drives_right
RU           200  Russia          True

In [96]:
#above method2
medium2 = cars1[np.logical_and(cars1.cars_per_cap<500,cars1.cars_per_cap>100)]

medium2

cars_per_cap country  drives_right
RU           200  Russia          True

In [97]:
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

army = pd.DataFrame(raw_data, columns = ['regiment','company','deaths','battles', 'size', 'veterans', 'readiness', 'armored', 'deserters', 'origin'])

In [98]:
#Set the 'origin' colum as the index of the dataframe
army.set_index('origin', inplace = True)
army

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                       
Arizona     Nighthawks     1st     523        5  1045         1          1   
California  Nighthawks     1st      52       42   957         5          2   
Texas       Nighthawks     2nd      25        2  1099        62          3   
Florida     Nighthawks     2nd     616        2  1400        26          3   
Maine         Dragoons     1st      43        4  1592        73          2   
Iowa          Dragoons     1st     234        7  1006        37          1   
Alaska        Dragoons     2nd     523        8   987       949          2   
Washington    Dragoons     2nd      62        3   849        48          3   
Oregon          Scouts     1st      62        4   973        48          2   
Wyoming         Scouts     1st      73        7  1005       435          1   
Louisana        Scouts     2nd      37        8  1099        63          2   
Georgia         Scouts     2nd      35        9  1523       345          3   

            armored  deserters  
origin                          
Arizona           1          4  
California        0         24  
Texas             1         31  
Florida           1          2  
Maine             0          3  
Iowa              1          4  
Alaska            0         24  
Washington        1         31  
Oregon            0          2  
Wyoming           0          3  
Louisana          1          2  
Georgia           1          3

In [99]:
#Print only the column veterans
army.veterans

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

In [101]:
#Print the columns 'veterans' and 'deaths'
army[['veterans' , 'deaths']]

veterans  deaths
origin                      
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

In [102]:
army.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

In [110]:
#Select the 'deaths', 'size' and 'deserters' columns from Maine and Alaska
army.loc[['Maine', 'Alaska']][['deaths','size','deserters']]

deaths  size  deserters
origin                         
Maine       43  1592          3
Alaska     523   987         24

In [112]:
#Select the rows 3 to 7 and the columns 3 to 6 #ASk ANIL

army.iloc[2:7,2:6]

deaths  battles  size  veterans
origin                                  
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

In [113]:
#Select every row after the fourth row
army.iloc[3:,:]

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                       
Florida     Nighthawks     2nd     616        2  1400        26          3   
Maine         Dragoons     1st      43        4  1592        73          2   
Iowa          Dragoons     1st     234        7  1006        37          1   
Alaska        Dragoons     2nd     523        8   987       949          2   
Washington    Dragoons     2nd      62        3   849        48          3   
Oregon          Scouts     1st      62        4   973        48          2   
Wyoming         Scouts     1st      73        7  1005       435          1   
Louisana        Scouts     2nd      37        8  1099        63          2   
Georgia         Scouts     2nd      35        9  1523       345          3   

            armored  deserters  
origin                          
Florida           1          2  
Maine             0          3  
Iowa              1          4  
Alaska            0         24  
Washington        1         31  
Oregon            0          2  
Wyoming           0          3  
Louisana          1          2  
Georgia           1          3

In [114]:
#Select every row up to the 4th row
army.iloc[:3]

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                       
Arizona     Nighthawks     1st     523        5  1045         1          1   
California  Nighthawks     1st      52       42   957         5          2   
Texas       Nighthawks     2nd      25        2  1099        62          3   

            armored  deserters  
origin                          
Arizona           1          4  
California        0         24  
Texas             1         31

In [117]:
#Select the 3rd column up to the 7th column
army.iloc[:,3:7]

battles  size  veterans  readiness
origin                                        
Arizona           5  1045         1          1
California       42   957         5          2
Texas             2  1099        62          3
Florida           2  1400        26          3
Maine             4  1592        73          2
Iowa              7  1006        37          1
Alaska            8   987       949          2
Washington        3   849        48          3
Oregon            4   973        48          2
Wyoming           7  1005       435          1
Louisana          8  1099        63          2
Georgia           9  1523       345          3

In [118]:
#Select rows where df.deaths is greater than 50
army[army['deaths']>50]

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                       
Arizona     Nighthawks     1st     523        5  1045         1          1   
California  Nighthawks     1st      52       42   957         5          2   
Florida     Nighthawks     2nd     616        2  1400        26          3   
Iowa          Dragoons     1st     234        7  1006        37          1   
Alaska        Dragoons     2nd     523        8   987       949          2   
Washington    Dragoons     2nd      62        3   849        48          3   
Oregon          Scouts     1st      62        4   973        48          2   
Wyoming         Scouts     1st      73        7  1005       435          1   

            armored  deserters  
origin                          
Arizona           1          4  
California        0         24  
Florida           1          2  
Iowa              1          4  
Alaska            0         24  
Washington        1         31  
Oregon            0          2  
Wyoming           0          3

In [119]:
#Select rows where df.deaths is greater than 500 or less than 50

army[np.logical_or(army['deaths']>500,army['deaths']<50)]

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                     
Arizona   Nighthawks     1st     523        5  1045         1          1   
Texas     Nighthawks     2nd      25        2  1099        62          3   
Florida   Nighthawks     2nd     616        2  1400        26          3   
Maine       Dragoons     1st      43        4  1592        73          2   
Alaska      Dragoons     2nd     523        8   987       949          2   
Louisana      Scouts     2nd      37        8  1099        63          2   
Georgia       Scouts     2nd      35        9  1523       345          3   

          armored  deserters  
origin                        
Arizona         1          4  
Texas           1         31  
Florida         1          2  
Maine           0          3  
Alaska          0         24  
Louisana        1          2  
Georgia         1          3

In [129]:
#Select rows where df.deaths is greater than 500 or less than 50
#method 2
army[(army['deaths']>500) | (army['deaths']<50)]


regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                     
Arizona   Nighthawks     1st     523        5  1045         1          1   
Texas     Nighthawks     2nd      25        2  1099        62          3   
Florida   Nighthawks     2nd     616        2  1400        26          3   
Maine       Dragoons     1st      43        4  1592        73          2   
Alaska      Dragoons     2nd     523        8   987       949          2   
Louisana      Scouts     2nd      37        8  1099        63          2   
Georgia       Scouts     2nd      35        9  1523       345          3   

          armored  deserters  
origin                        
Arizona         1          4  
Texas           1         31  
Florida         1          2  
Maine           0          3  
Alaska          0         24  
Louisana        1          2  
Georgia         1          3

In [130]:
army[army.regiment != "Dragoons"]  #Select all the regiments not named "Dragoons"

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                       
Arizona     Nighthawks     1st     523        5  1045         1          1   
California  Nighthawks     1st      52       42   957         5          2   
Texas       Nighthawks     2nd      25        2  1099        62          3   
Florida     Nighthawks     2nd     616        2  1400        26          3   
Oregon          Scouts     1st      62        4   973        48          2   
Wyoming         Scouts     1st      73        7  1005       435          1   
Louisana        Scouts     2nd      37        8  1099        63          2   
Georgia         Scouts     2nd      35        9  1523       345          3   

            armored  deserters  
origin                          
Arizona           1          4  
California        0         24  
Texas             1         31  
Florida           1          2  
Oregon            0          2  
Wyoming           0          3  
Louisana          1          2  
Georgia           1          3

In [133]:
#Select the rows called Texas and Arizona

army.loc[["Texas","Arizona"]]

regiment company  deaths  battles  size  veterans  readiness  \
origin                                                                    
Texas    Nighthawks     2nd      25        2  1099        62          3   
Arizona  Nighthawks     1st     523        5  1045         1          1   

         armored  deserters  
origin                       
Texas          1         31  
Arizona        1          4

In [141]:
#Select the third cell in the row named Arizona
army.loc[["Arizona"]]['deaths']

origin
Arizona    523
Name: deaths, dtype: int64

In [165]:
#Select the third cell in the row named Arizona - anothermethod
army.loc["Arizona"].iloc[2]
#army.loc[["Arizona"]].iloc[:,2]

523

In [172]:
#Select the third cell down in the column named deaths
army.iloc[[2]]["deaths"]

origin
Texas    25
Name: deaths, dtype: int64