In [2]:
import numpy as np

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [4]:
from numpy import array

In [6]:
array([1,2,3])

array([1, 2, 3])

In [7]:
aray1 = np.array(["ab","cd","ef"])


array(['ab', 'cd', 'ef'], dtype='<U2')

In [8]:
aray1

array(['ab', 'cd', 'ef'], dtype='<U2')

In [9]:
height = [1.73,2.3,5.6,2.3]

In [10]:
weight = [65.4,56.7,72.1,45.8]

In [12]:
weight/height*2

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [13]:
npheight = np.array(height)
npheight

array([1.73, 2.3 , 5.6 , 2.3 ])

In [14]:
npweight = np.array(weight)

In [16]:
bmi = npweight/npheight**2

In [17]:
bmi

array([21.85171573, 10.71833648,  2.29910714,  8.65784499])

In [30]:
np1 = np.array([11,22,33,44])

In [29]:
np2 = np.array([5,4,3,2])

In [31]:
np3 = np1*np2
np3

array([55, 88, 99, 88])

In [41]:
np4 = np.array([[11,22,33,44],[5,4,3,2]])
np4

array([[11, 22, 33, 44],
       [ 5,  4,  3,  2]])

In [34]:
np4.shape #tells rows and columns

(2, 4)

In [37]:
np4[0]

array([11, 22, 33, 44])

In [38]:
np4[0,1] #slicing in array

22

In [39]:
np4[0][-1]

44

In [40]:
np4[1,0]

5